name: GHAction zad2  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/zad2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/qwe357/zad2:${{ github.sha }} .

      - name: Scan Docker image with Docker Scout
        id: scan
        run: |
          docker scout quickview docker.io/qwe357/zad2:${{ github.sha }}
        continue-on-error: false

      - name: Tag Docker image with new tag
        if: success()
        run: docker tag docker.io/qwe357/zad2:${{ github.sha }} docker.io/qwe357/zad2:succeed
        
      - name: Push the Docker image
        if: success()
        run: docker image push docker.io/qwe357/zad2:succeed
