name: GHAction zad2  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag, test and push Docker image
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/zad2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false  # Build image but do not push yet
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache  
          tags: ${{ steps.meta.outputs.tags }}

      - 
        name: Scan Docker image for vulnerabilities
        uses: docker/scout-action@v1
        with:
          image: ${{ vars.DOCKERHUB_USERNAME }}/zad2:latest
          command: cves
        

      - 
        name: Check for critical or high vulnerabilities
        run: |
          critical_count=$(jq '.summary.critical' < scan-results.json)
          high_count=$(jq '.summary.high' < scan-results.json)
          if [ "$critical_count" -ne "0" ] || [ "$high_count" -ne "0" ]; then
            echo "Image contains critical or high vulnerabilities. Failing the build."
            exit 1
          fi

      - 
        name: Push Docker image to DockerHub
        if: success()  # Only push if the scan passes
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache  
          tags: ${{ steps.meta.outputs.tags }}
